config/routes.rb
Rails.application.routes.draw do
  resources :artworks
  devise_for :users
  root "home#page", as: "home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artwork.rb
class Artwork < ApplicationRecord
    has_one_attached :picture
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :detect_admin, :only => [:new, :edit, :create, :destroy]
  before_action :set_artwork, only: %i[ show edit update destroy ]

  # GET /artworks or /artworks.json
  def index
    @artworks = Artwork.all
  end

  # GET /artworks/1 or /artworks/1.json
  def show
  end

  # GET /artworks/new
  def new
    @artwork = Artwork.new
  end

  # GET /artworks/1/edit
  def edit
  end

  # POST /artworks or /artworks.json
  def create
    @artwork = Artwork.new(artwork_params)

    respond_to do |format|
      if @artwork.save
        format.html { redirect_to @artwork, notice: "Artwork was successfully created." }
        format.json { render :show, status: :created, location: @artwork }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artworks/1 or /artworks/1.json
  def update
    respond_to do |format|
      if @artwork.update(artwork_params)
        format.html { redirect_to @artwork, notice: "Artwork was successfully updated." }
        format.json { render :show, status: :ok, location: @artwork }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artworks/1 or /artworks/1.json
  def destroy
    @artwork.destroy
    respond_to do |format|
      format.html { redirect_to artworks_url, notice: "Artwork was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artwork
      @artwork = Artwork.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artwork_params
      params.require(:artwork).permit(:title, :year, :medium, :size, :price, :picture)
    end


    #Give admin permissions if User is an admin
    def detect_admin
      authenticate_user!
    
      if current_user.admin
         return
      else
         redirect_to home_path
         flash[:alert] = "You must be an admin to do that."

      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def page
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/artworks/_form.html.erb
<%= simple_form_for(@artwork) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :year %>
    <%= f.input :medium %>
    <%= f.input :size %>
    <%= f.input :price %>
    <%= f.file_field :picture %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/artworks/edit.html.erb
<h1>Editing Artwork</h1>

<%= render 'form', artwork: @artwork %>

<%= link_to 'Show', @artwork %> |
<%= link_to 'Back', artworks_path %>

app/views/artworks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gallery</h1>

<div class="gallery">
    <% @artworks.each do |artwork| %>
      <div class="index-card">
        <div class="index-image">
            <%= image_tag artwork.picture %>
          </div>
        <p class="artwork-title"><%= artwork.title %></p>
        <p><%=  artwork.year %></p>
        <%= link_to  'Details', artwork_path(artwork.id)  %>
      <% if current_user.admin %>
      <ul>
        <li><%= link_to 'Show', artwork %></li>
        <li><%= link_to 'Edit', edit_artwork_path(artwork) %></li>
        <li><%= link_to 'Destroy', artwork, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
      <% end %>
    </div>
      
    <% end %>
</div>

<br>

<% if current_user.admin %>
<%= link_to 'New Artwork', new_artwork_path %>
<% end %>

app/views/artworks/new.html.erb
<h1>New Artwork</h1>

<%= render 'form', artwork: @artwork %>

<%= link_to 'Back', artworks_path %>

app/views/artworks/show.html.erb
<p id="notice"><%= notice %></p>
        <div class="artwork-card">
          <div class="show-image">
            <%= image_tag @artwork.picture %>
          </div>
          
          <div class="artwork-info">
            <p>
              <strong>Title:</strong>
              <%= @artwork.title %>
            </p>

            <p>
              <strong>Year:</strong>
              <%= @artwork.year %>
            </p>

            <p>
              <strong>Medium:</strong>
              <%= @artwork.medium %>
            </p>

            <p>
              <strong>Size:</strong>
              <%= @artwork.size %>
            </p>

            <p>
              <strong>Price:</strong>
              <%= @artwork.price %>
            </p>
          <div>
        <% if current_user.admin %>
          <%= link_to 'Edit', edit_artwork_path(@artwork) %> |
        <% end %>
<%= link_to 'Back', artworks_path %>
 </div>

app/views/home/page.html.erb
        <div class="jumbotron">
        <div class="row">
            <div class="col-md-6">
            <h1 class="display-4">Welcome</h1>
            <p class="lead">Theo Harris is a visual artist from Sydney, Australia.</p>
            <hr class="my-4">
            <p>His work explores themes of alienation, self-image and the queer Other.</p>
            <% if current_user.admin %>
            <p class="lead">
                <%= link_to "Create Artwork", new_artwork_path, class: "btn btn-primary btn-lg" %>
            </p>
            <% end %>
            </div>

            <div class="col-md-6">
                <%= image_tag "Pencil-Purple-Lorikeet.png", class: "home-image" %>
            </div>
            <div>

        </div>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsArtistPortfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  

  <body>
  <div class="container">
  <%= render "partials/navbar" %>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
  </body>
</html>

app/views/partials/_navbar.html.erb
<head>
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
</head>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Theo Harris</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/artworks">Gallery</a>
        </li>
        
        <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
        <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>